name: reflect-extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
      - uses: actions/setup-node@v1
        with:
          version: '12.x'
      - name: Compile code
      - run: |
          npm install
          npm run build
      - name: Run unit tests
      - run: npm test
        run: npm test
