name: Publish package

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Compile code
        run: |
          npm install
          npm run build
      - name: Run unit tests
        run: npm test
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Publish package
        run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
